language: node_js

node_js:
  - "stable"

services:
  - mongodb

cache:
  directories:
    - node_modules

script:
  - cd backend
  - yarn install
  - yarn testCI
  - yarn lint
  - cd ..
  - cd frontend
  - yarn install
  - yarn lint
  - "CI=true yarn test"
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: frontend/build
  on:
    branch: master

notifications:
  email:
    recipients:
      - jfischetti94@gmail.com
      - alvaropiorno100@gmail.com
      - garciasmithagustin@gmail.com
    on_success: change
    on_failure: always
