scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['10.12.2.37:3001']
        labels:
          service: 'rev-ind'
          group: 'production'
